title = "Jaffar"
base_url = "https://jaffar.me"
description = "Passionate solutions architect, and a developer."
theme = "duckquill"

compile_sass = true
minify_html = true
generate_feeds = true
build_search_index = false
author = "Jaffar"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
smart_punctuation = true

[extra]
primary_color = "#00d992"
animated_favicon = true
stylesheets = ["custom.css"]
show_copy_button = true

[extra.nav]
show_feed = false
links = [
  { url = "@/about/index.md", name = "About" },
  { url = "@/blog/_index.md", name = "Blog" },
]

[extra.footer]
show_copyright = true
show_powered_by = true
